mapping_name: 'ansible-test-mapping'
mapping_name_2: 'ansible-test-mapping-2'
mapping_rules_1:
- local:
  - group:
      domain:
        name: example_domain
      name: example-group
  remote:
  - type: HTTP_OIDC_GROUPS
    any_one_of:
    - group1
    - group2
mapping_rules_2:
- local:
  - group:
      domain:
        name: example_domain
      name: example_group
  remote:
  - type: HTTP_OIDC_GROUPS
    any_one_of:
    - group1
