---

- name: Get nova compute services info
  openstack.cloud.compute_service_info:
    cloud: "{{ cloud }}"
  register: result
  failed_when: "result.openstack_compute_services | length <= 0"

- name: Assert fields on OpenStack SDK before 0.53
  when: sdk_version is version(0.53, '<')
  assert:
    that:
    - '["availability_zone", "binary", "disables_reason", "is_forced_down",
        "host", "name", "state", "status", "updated_at", "id"] |
        difference(result.openstack_compute_services.0.keys()) | length == 0'

- name: Assert fields on OpenStack SDK 0.53 and later
  when: sdk_version is version(0.53, '>=')
  assert:
    that:
    - '["availability_zone", "binary", "disabled_reason", "is_forced_down",
        "host", "name", "state", "status", "updated_at", "id"] |
        difference(result.openstack_compute_services.0.keys()) | length == 0'

- name: Filter compute services. Supported since OpenStack SDK 0.53.0 (Wallaby).
  when: sdk_version is version(0.53, '>=')
  block:
  - name: Get nova compute services info
    openstack.cloud.compute_service_info:
      cloud: "{{ cloud }}"
      binary: "nova-compute"
    register: result
    failed_when: "result.openstack_compute_services | length <= 0"
