image_name: ansible_image
image_tags:
  - test
  - ansible
expected_fields:
  - architecture
  - checksum
  - container_format
  - created_at
  - direct_url
  - disk_format
  - file
  - has_auto_disk_config
  - hash_algo
  - hash_value
  - hw_cpu_cores
  - hw_cpu_policy
  - hw_cpu_sockets
  - hw_cpu_thread_policy
  - hw_cpu_threads
  - hw_disk_bus
  - hw_machine_type
  - hw_qemu_guest_agent
  - hw_rng_model
  - hw_scsi_model
  - hw_serial_port_count
  - hw_video_model
  - hw_video_ram
  - hw_vif_model
  - hw_watchdog_action
  - hypervisor_type
  - id
  - instance_type_rxtx_factor
  - instance_uuid
  - is_hidden
  - is_hw_boot_menu_enabled
  - is_hw_vif_multiqueue_enabled
  - is_protected
  - kernel_id
  - locations
  - metadata
  - min_disk
  - min_ram
  - name
  - needs_config_drive
  - needs_secure_boot
  - os_admin_user
  - os_command_line
  - os_distro
  - os_require_quiesce
  - os_shutdown_timeout
  - os_type
  - os_version
  - owner
  - owner_id
  - properties
  - ramdisk_id
  - schema
  - size
  - status
  - store
  - tags
  - updated_at
  - url
  - virtual_size
  - visibility
  - vm_mode
  - vmware_adaptertype
  - vmware_ostype
